### ISSUE TITLE
no feature_frontend in vins_so

### ISSUE THREAD

**Issue by ethanguo0327** [gaowenliang/vins_so#3]
Im going to try vins-so with dual-fisheye camera,but in the dual-fisheye.launch,it needs feature_frontend and fisheye_model.
I find the feature_frontend ,but it needs vignetting_model；
And I cant find fisheye_model either.
So are you willing to share these codes? @gaowenliang thanks in advance

**Comment by gaowenliang** [comment]
It is another repo
